### ISSUE TITLE
Not able to do `ember install ember-electron`

### ISSUE THREAD

**Issue by cohki0305** [felixrieseberg/ember-electron#197]
Hello, 

I got an error when I was installing ember-electorn.
Please tell me a solution.

I'm sorry if it was a rudimentary question. 
I did not understand even if I started by just starting it.

**what I did**

```
$ ember new my-project
$ cd electron-my-project
$ ember install ember-electron
```

**Error message**

Error message is following.

```
lock-scoped declarations (let, const, function, class) not yet supported outside strict mode
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at 
```

**Env**

```
npm version -> 4.4.1

```

**Comment by pichfl** [comment]
As we note in our [documentation](https://github.com/felixrieseberg/ember-electron/blob/master/docs/guides/installation.md) this plugin requires at least Node 6.
