### ISSUE TITLE
Components Error

### ISSUE THREAD

**Issue by FernandoGOT** [felixrieseberg/ember-electron#21]
I cerated a new ember project, I basically copied the ember tuto from https://guides.emberjs.com/v2.3.0/

The site is working correctly in the browser, but the electron just load a blank page. I created a new empty project and this one is working correctly.

the error that I get is this:

```
8. Integration | Component | rental listing: it renders (2, 0, 2)Rerun168 ms
1. failed@ 140 ms
Expected: 	
""
Result: 	
"Owner: 
Type: 
Location: 
Number of bedrooms: 
  Show image"
Source: 	
    at Object.<anonymous> (file:///Users/fernandogot/projects/ember/electron/tmp/class-tests_dist_electron-7tcZC0FG.tmp/assets/tests.js:210:12)
2. failed@ 147 ms
Expected: 	
"template block text"
Result: 	
"Owner: 
Type: 
Location: 
Number of bedrooms: 
  Show image"
Diff: 	
"templOwner: 
Type: 
Location: 
Number of block textedrooms: 
  Show image"
Source: 	
    at Object.<anonymous> (file:///Users/fernandogot/projects/ember/electron/tmp/class-tests_dist_electron-7tcZC0FG.tmp/assets/tests.js:294:12)
Source: at testWrapper (file:///Users/fernandogot/projects/ember/electron/tmp/class-tests_dist_electron-7tcZC0FG.tmp/assets/test-support.js:6400:11)

```

the problem is probably in this component:

https://guides.emberjs.com/v2.3.0/tutorial/simple-component/

**Comment by FernandoGOT** [comment]
I did some tests here and find the error being on the ember tests
