### ISSUE TITLE
2.0.0-beta.4 Failed to install modules "electron-compile"

### ISSUE THREAD

**Issue by li-xinyang** [felixrieseberg/ember-electron#215]
I am having issue with version 1.x so I decided to try 2.x; however, I encounter the following issue after `npm install`,

```
➜  RR_VEE_2_Web git:(master) ✗ ember g ember-electron
installing ember-electron
  identical ember-electron/.compilerc
  identical ember-electron/.eslintrc.js
  identical ember-electron/main.js
  identical testem-electron.js
  identical tests/ember-electron/.eslintrc.js
  identical tests/ember-electron/main.js
Project needs forge config
⠼ Installing electron build toolsFailed to install modules: ["electron-compile"]

With output: yarn add v0.21.3
info No lockfile found.
[1/4] Resolving packages...
warning glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning ember-cli-qunit > broccoli-babel-transpiler > babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning electron-prebuilt-compile > electron-compilers > jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning ember-electron > electron-forge > zip-folder > archiver > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning electron-prebuilt-compile > electron-compilers > jade > transformers@2.1.0: Deprecated, use jstransformer
warning ember-electron > npmi > npm > request > node-uuid@1.4.8: Use uuid module instead
warning ember-electron > electron-forge > electron-windows-store > flatten-packages > wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
warning ember-electron > electron-forge > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
warning appdmg@0.4.5: The platform "linux" is incompatible with this module.
info "appdmg@0.4.5" is an optional dependency and failed compatibility check. Excluding it from installation.
error macos-alias@0.2.11: The platform "linux" is incompatible with this module.
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

After run `ember g ember-electron`, the `package.json` file seems changed so I run `npm install` again to install the new dependencies with no error.

And then I try re-run `ember electron` and I got the following error,

```
Starting Electron...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/li-xinyang/Desktop/RR_VEE_2_Web/tmp/electron_livereload-WqfKbd4M.tmp/node_modules/.bin/electron ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by li-xinyang** [comment]
The issue can be solved by removing `yarn` https://github.com/felixrieseberg/ember-electron/issues/214.
