### ISSUE TITLE
App threw an error during load Electron

### ISSUE THREAD

**Issue by li-xinyang** [felixrieseberg/ember-electron#216]
After,

```
npm install # with latest version of ember-electron
ember g ember-electron
ember electron
```

I got the following errors,

```
Starting Electron...
App threw an error during load
Error: Cannot find module '/home/li-xinyang/Desktop/RR_VEE_2_Web/tmp/electron_livereload-qzj2srOT.tmp'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/li-xinyang/Desktop/RR_VEE_2_Web/node_modules/electron-prebuilt-compile/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at init (/home/li-xinyang/Desktop/RR_VEE_2_Web/node_modules/electron-compile/lib/config-parser.js:292:16)
    at main (/home/li-xinyang/Desktop/RR_VEE_2_Web/node_modules/electron-prebuilt-compile/lib/es6-init.js:40:29)
    at Object.<anonymous> (/home/li-xinyang/Desktop/RR_VEE_2_Web/node_modules/electron-prebuilt-compile/lib/es6-init.js:43:1)
    at Object.<anonymous> (/home/li-xinyang/Desktop/RR_VEE_2_Web/node_modules/electron-prebuilt-compile/lib/es6-init.js:45:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/home/li-xinyang/Desktop/RR_VEE_2_Web/tmp/electron_livereload-qzj2srOT.tmp'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/li-xinyang/Desktop/RR_VEE_2_Web/node_modules/electron-prebuilt-compile/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at init (/home/li-xinyang/Desktop/RR_VEE_2_Web/node_modules/electron-compile/lib/config-parser.js:292:16)
    at main (/home/li-xinyang/Desktop/RR_VEE_2_Web/node_modules/electron-prebuilt-compile/lib/es6-init.js:40:29)
    at Object.<anonymous> (/home/li-xinyang/Desktop/RR_VEE_2_Web/node_modules/electron-prebuilt-compile/lib/es6-init.js:43:1)
    at Object.<anonymous> (/home/li-xinyang/Desktop/RR_VEE_2_Web/node_modules/electron-prebuilt-compile/lib/es6-init.js:45:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

**Comment by koopa** [comment]
@li-xinyang I am facing the same problem after updating `ember-electron` from `1.x` to `2.0` and found this issue.

Have you perhaps already gained some more insight in the meantime?

**Comment by bendemboski** [comment]
I think I've seen that when the main Javascript file was missing from the built package. If you have a `main` entry in your `package.json`, make sure that the path it points to is somewhere inside the `ember-electron` directory, and that the file exists. If you don't have a `main` entry in your `package.json`, it will default to `ember-electron/main.js`, so make sure that file exists.

Running `ember g ember-electron` should set a working configuration, but I don't know if we've tested all the various upgrade scenarios.

**Comment by koopa** [comment]
That was really helpful, many thanks @bendemboski!
"main" was indeed still holding the string "electron.js".

**Comment by benoror** [comment]
Same issue here, thanks for the tip! 

BTW, should this be included in the blueprint?

**Comment by bendemboski** [comment]
Ah, right. So here's the story -- you actually don't need a `main` entry in your `package.json`. If it's not there, it will end up defaulting to `ember-electron/main.js`. However, if you do have a `main` entry, then it is expected to point to the file you actually want to execute as the entry point to your main process. So, since you two had a `main` entry presumably left over from v1 pointing to `electron.js`, it was overriding the default, but per the v2 blueprint, your main file is at the default location of `ember-electron/main.js`.

So, you should be able to just delete the `main` entry from your package.json entirely. But we should do a better job of addressing this issue.

@anulman @pichfl your thoughts here? We could just make a note in the upgrade guide/faq, or we could look into modifying the blueprint to delete `main` out of `package.json`? Or perhaps only target the v1->v2 upgrade case, and only delete it if it points to `electron.js`?

Either way, I think it makes sense to ensure that the `main` entry points to a file that exists when running `ember electron` (probably any `ember electron:*` command), and if not bail with a more descriptive error than the super-cryptic one that these folks had to deal with (sorry, friends!). Or perhaps this `main` verification belongs upstream in `electron-forge` -- @anulman your thoughts?

**Comment by pichfl** [comment]
Extracted enhancement into new ticket, closing this.
