### ISSUE TITLE
Cannot create windows package from linux

### ISSUE THREAD

**Issue by talhaobject90** [felixrieseberg/ember-electron#23]
Here the details of my environment:

ubuntu 12.04 (64-bit)
Node version v4.2.4
ember 2.2.2
"ember-electron": "0.3.4",

while creating package using ember electron:package
Packaging app for platform win32 ia32 using electron v0.36.2

Error packaging your Ember app into an Electron executable:

```
Error: spawn wine ENOENT
spawn wine ENOENT
Error: spawn wine ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

But , I am able to create linux packages. and run it.

But this windows issue stucks . I wonder if http://stackoverflow.com/a/31327872/3286320 could be a solution. But no more details there how to implement it and where.

**Comment by talhaobject90** [comment]
update:
My attempt to build x64 package is failed ,

```x303-systems@x303systems-Inspiron-3541:/var/www/signlab/signlab-ember$ ember electron:package --platform win32 --arch x64
version: 1.13.12
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Building[Deprecated] new this.Funnel(..) is deprecated, please use broccoli-funnel directly instead  [addon: ember-paper]
[Deprecated] new this.Funnel(..) is deprecated, please use broccoli-funnel directly instead  [addon: liquid-fire]
Built project successfully. Stored in "./tmp/electron-build-tmp/dist".
Installing production dependencies into Electron Build Package
Installed and bundled ember-cli-lightbox@0.0.3
Packaging app for platform win32 x64 using electron v0.36.2

Error packaging your Ember app into an Electron executable:

Error: ENOENT: no such file or directory, mkdir '/tmp/electron-packager/win32-x64/signlab-ember-win32-x64/resources/app'
Error: ENOENT: no such file or directory, mkdir '/tmp/electron-packager/win32-x64/signlab-ember-win32-x64/resources/app'
```

I tried creating that directory manually but failed

**Comment by felixrieseberg** [comment]
Well, do you have wine installed?

**Comment by talhaobject90** [comment]
@felixrieseberg  , 
No . is it required to just generate windows package?

**Comment by felixrieseberg** [comment]
Yeah! You need some basic libraries to compile ;-) I'm closing this then.
