### ISSUE TITLE
Failed to locate makeable Electron application

### ISSUE THREAD

**Issue by kedano** [felixrieseberg/ember-electron#236]
I have an ember v2.12.1 app that runs just fine on OSX 10.12.4 in the evergreen browsers. `$ ember electron:package` works as expected and creates a mac application. Same if I specify `-p win32`.

When I try to run the make command the following happens:

```
$ ember electron:make

...

Packaging Electron project.
✔ Preparing to Package Application for arch: x64
✔ Compiling Application
✔ Preparing native dependencies
✔ Packaging Application
Making Electron project.
Failed to locate makeable Electron application
```

Any way to add some debug flags to see where it fails?

**Comment by pichfl** [comment]
Which version of Ember Electron do you use?

**Comment by kedano** [comment]
I installed the latest version, v2.1.0. I installed Wine v2.0.1 with homebrew.

**Comment by bendemboski** [comment]
@kedano can you run like this:

```
DEBUG=electron-forge:project-resolver ember electron:make
```

and paste the output (starting with "Packaging Electron project." like you did above) here?

**Comment by kedano** [comment]
My first output was:

```
Packaging Electron project.
  electron-forge:project-resolver searching for project in: /Users/keda/projects/hiof-semesterstart-admin/tmp/package_task-tmp_path-cCKUGCvA.tmp +0ms
  electron-forge:project-resolver electron-forge compatible package.json found in /Users/keda/projects/hiof-semesterstart-admin/tmp/package_task-tmp_path-cCKUGCvA.tmp/package.json +4ms
EEXIST: file already exists, link '/var/folders/vl/lg91hb6s789ctybm_hccms_r0000gn/T/electron-packager/darwin-x64/semesterstart-admin-darwin-x64' -> 'electron-out/semesterstart-admin-darwin-x64'
Error: EEXIST: file already exists, link '/var/folders/vl/lg91hb6s789ctybm_hccms_r0000gn/T/electron-packager/darwin-x64/semesterstart-admin-darwin-x64' -> 'electron-out/semesterstart-admin-darwin-x64'
    at Error (native)
```

It looks like it failed due to not being able to delete the files/folders in `electron-out`. I removed the folders and tried to run the debug command again. Now I got the following error:

```
Packaging Electron project.
  electron-forge:project-resolver searching for project in: /Users/keda/projects/hiof-semesterstart-admin/tmp/package_task-tmp_path-xWq4tfkC.tmp +0ms
  electron-forge:project-resolver electron-forge compatible package.json found in /Users/keda/projects/hiof-semesterstart-admin/tmp/package_task-tmp_path-xWq4tfkC.tmp/package.json +3ms
Making Electron project.
  electron-forge:project-resolver searching for project in: /Users/keda/projects/hiof-semesterstart-admin +4s
  electron-forge:project-resolver searching for project in: /Users/keda/projects +1ms
  electron-forge:project-resolver searching for project in: /Users/keda +0ms
  electron-forge:project-resolver searching for project in: /Users +0ms
  electron-forge:project-resolver searching for project in: / +0ms
Failed to locate makeable Electron application
```

I previously had version v1.12.7 installed and updated to the latest version v2.1.0 in my package.json file, `npm install` and then `ember generate ember-electron`.

**Comment by tobiasWenger** [comment]
same problem with complete fresh installation:

ember-cli: 2.12.1,
node: 6.10.2,
os: win32 x64
electron: 2.1.1

packaging works fine but I get the same error when running electron:make

**Comment by pichfl** [comment]
Can confirm in an empty project on 

> ember-cli: 2.12.1
> node: 7.7.3
> os: darwin x64

```bash
eedemo git/master  12s
❯ DEBUG=electron-forge:* ember electron:make
WARNING: DEBUG environment variable detected.  Progress indicators will be sent over electron-forge:lifecycle

"ember-welcome-page" was detected in your devDependencies!
Please note that this addon only works in development environment
and will not render in production mode. It is safe to uninstall
this addon once you removed the {{welcome-page}} template tag.

cleaning up...
Built and assembled Electron project successfully. Stored in "/Users/pichfl/Desktop/eedemo/tmp/package_task-tmp_path-HW3N5cUl.tmp".
⠇ installing production dependencieseedemo@0.0.0 /Users/pichfl/Desktop/eedemo/tmp/package_task-tmp_path-HW3N5cUl.tmp
├─┬ electron-compile@6.4.0
│ ├─┬ @paulcbetts/mime-types@2.1.10
│ │ └── @paulcbetts/mime-db@1.22.4
│ ├── @types/node@7.0.13
│ ├── btoa@1.1.2
│ ├─┬ debug@2.6.3
│ │ └── ms@0.7.2
│ ├─┬ lru-cache@4.0.2
│ │ ├── pseudomap@1.0.2
│ │ └── yallist@2.1.2
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── pify@2.3.0
│ ├─┬ rimraf@2.6.1
│ │ └─┬ glob@7.1.1
│ │   ├── fs.realpath@1.0.0
│ │   ├─┬ inflight@1.0.6
│ │   │ └── wrappy@1.0.2
│ │   ├── inherits@2.0.3
│ │   ├─┬ minimatch@3.0.3
│ │   │ └─┬ brace-expansion@1.1.7
│ │   │   ├── balanced-match@0.4.2
│ │   │   └── concat-map@0.0.1
│ │   ├── once@1.4.0
│ │   └── path-is-absolute@1.0.1
│ ├─┬ rxjs@5.3.0
│ │ └── symbol-observable@1.0.4
│ ├─┬ spawn-rx@2.0.10
│ │ └── lodash.assign@4.2.0
│ └─┬ yargs@4.8.1
│   ├─┬ cliui@3.2.0
│   │ ├─┬ strip-ansi@3.0.1
│   │ │ └── ansi-regex@2.1.1
│   │ └── wrap-ansi@2.1.0
│   ├── decamelize@1.2.0
│   ├── get-caller-file@1.0.2
│   ├─┬ os-locale@1.4.0
│   │ └─┬ lcid@1.0.0
│   │   └── invert-kv@1.0.0
│   ├─┬ read-pkg-up@1.0.1
│   │ ├─┬ find-up@1.1.2
│   │ │ ├── path-exists@2.1.0
│   │ │ └─┬ pinkie-promise@2.0.1
│   │ │   └── pinkie@2.0.4
│   │ └─┬ read-pkg@1.1.0
│   │   ├─┬ load-json-file@1.1.0
│   │   │ ├── graceful-fs@4.1.11
│   │   │ ├─┬ parse-json@2.2.0
│   │   │ │ └─┬ error-ex@1.3.1
│   │   │ │   └── is-arrayish@0.2.1
│   │   │ └─┬ strip-bom@2.0.0
│   │   │   └── is-utf8@0.2.1
│   │   ├─┬ normalize-package-data@2.3.6
│   │   │ ├── hosted-git-info@2.4.2
│   │   │ ├─┬ is-builtin-module@1.0.0
│   │   │ │ └── builtin-modules@1.1.1
│   │   │ ├── semver@5.3.0
│   │   │ └─┬ validate-npm-package-license@3.0.1
│   │   │   ├─┬ spdx-correct@1.0.2
│   │   │   │ └── spdx-license-ids@1.2.2
│   │   │   └── spdx-expression-parse@1.0.4
│   │   └── path-type@1.1.0
│   ├── require-directory@2.1.1
│   ├── require-main-filename@1.0.1
│   ├── set-blocking@2.0.0
│   ├─┬ string-width@1.0.2
│   │ ├── code-point-at@1.1.0
│   │ └─┬ is-fullwidth-code-point@1.0.0
│   │   └── number-is-nan@1.0.1
│   ├── which-module@1.0.0
│   ├── window-size@0.2.0
│   ├── y18n@3.2.1
│   └─┬ yargs-parser@2.4.1
│     └── camelcase@3.0.0
└─┬ electron-protocol-serve@1.3.0
  └─┬ mock-require@2.0.2
    └─┬ caller-id@0.1.0
      └── stack-trace@0.0.9

Packaging Electron project.
  electron-forge:lifecycle Process Started: Preparing to Package Application for arch: x64 +0ms
  electron-forge:project-resolver searching for project in: /Users/pichfl/Desktop/eedemo/tmp/package_task-tmp_path-HW3N5cUl.tmp +1ms
  electron-forge:project-resolver electron-forge compatible package.json found in /Users/pichfl/Desktop/eedemo/tmp/package_task-tmp_path-HW3N5cUl.tmp/package.json +3ms
  electron-forge:packager packaging with options { asar: false,
  overwrite: true,
  afterCopy: [ [Function], [Function], [Function], [Function] ],
  afterExtract: [],
  dir: '/Users/pichfl/Desktop/eedemo/tmp/package_task-tmp_path-HW3N5cUl.tmp',
  arch: 'x64',
  platform: 'darwin',
  out: 'electron-out',
  electronVersion: '1.6.2',
  quiet: true } +6ms
  electron-forge:lifecycle Process Succeeded: Preparing to Package Application for arch: x64 +2s
  electron-forge:lifecycle Process Started: Compiling Application +1ms
Failed to compile file: /var/folders/lg/3qdjv59s2bs7k2k8w1m1_l940000gn/T/electron-packager/darwin-x64/eedemo-darwin-x64/Electron.app/Contents/Resources/app/ember/crossdomain.xml
Compiling /var/folders/lg/3qdjv59s2bs7k2k8w1m1_l940000gn/T/electron-packager/darwin-x64/eedemo-darwin-x64/Electron.app/Contents/Resources/app/ember/crossdomain.xml resulted in a MIME type of application/xml, which we don't know how to handle
  electron-forge:lifecycle Process Succeeded: Compiling Application +552ms
  electron-forge:lifecycle Process Started: Preparing native dependencies +0ms
  electron-forge:lifecycle Process Succeeded: Preparing native dependencies +45ms
  electron-forge:lifecycle Process Started: Packaging Application +0ms
  electron-forge:lifecycle Process Succeeded: Packaging Application +668ms
Making Electron project.
  electron-forge:project-resolver searching for project in: /Users/pichfl/Desktop/eedemo +275ms
  electron-forge:project-resolver searching for project in: /Users/pichfl/Desktop +0ms
  electron-forge:project-resolver searching for project in: /Users/pichfl +0ms
  electron-forge:project-resolver searching for project in: /Users +1ms
  electron-forge:project-resolver searching for project in: / +0ms
Failed to locate makeable Electron application
```

**Comment by bendemboski** [comment]
Ah, nuts. Workaround for now is to add

```
  "config": {
    "forge": "./ember-electron/electron-forge-config.js"
  }
```

to your `package.json`. I'll noodle on the best way to fix this...

**Comment by tobiasWenger** [comment]
Many thanks and I really appreciate all the work done for this project.

**Comment by artemgurzhii** [comment]
@kedano Where are you running this command? I had the same problem and as I find out the problem was in [terminal-plus](https://github.com/jeremyramin/terminal-plus) package for the atom.
Running the command from terminal works fine for me.

**Comment by artemgurzhii** [comment]
Having almost same problem
```bash
Packaging Electron project.
✔ Preparing to Package Application for arch: x64
⠧ Compiling ApplicationFailed to compile file: /var/folders/54/1d9qj88x5ylg7n806wm_j0hr0000gq/T/electron-packager/darwin-x64/Calculator-darwin-x64/Electron.app/C
ontents/Resources/app/ember/crossdomain.xml
Compiling /var/folders/54/1d9qj88x5ylg7n806wm_j0hr0000gq/T/electron-packager/darwin-x64/Calculator-darwin-x64/Electron.app/Contents/Resources/app/ember/crossdoma
in.xml resulted in a MIME type of application/xml, which we don't know how to handle
✔ Compiling Application
✔ Preparing native dependencies
✔ Packaging Application
Making Electron project.
An error occured while making for target: dmg
spawn bless ENOENT
Error: spawn bless ENOENT
    at exports._errnoException (util.js:1034:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)

    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by bendemboski** [comment]
@artemgurzhii that is a different issue. We'd certainly be happy to figure out what's going wrong, but could you file it separately?

**Comment by artemgurzhii** [comment]
@bendemboski You want me to open new issue?

**Comment by bendemboski** [comment]
Yes please

**Comment by artemgurzhii** [comment]
@bendemboski Done [#240](https://github.com/felixrieseberg/ember-electron/issues/240)!
