### ISSUE TITLE
An error occured while making for target: dmg

### ISSUE THREAD

**Issue by artemgurzhii** [felixrieseberg/ember-electron#240]
I'm having following error when running `ember electron:pack`
```bash
Packaging Electron project.
✔ Preparing to Package Application for arch: x64
⠧ Compiling ApplicationFailed to compile file: /var/folders/54/1d9qj88x5ylg7n806wm_j0hr0000gq/T/electron-packager/darwin-x64/Calculator-darwin-x64/Electron.app/C
ontents/Resources/app/ember/crossdomain.xml
Compiling /var/folders/54/1d9qj88x5ylg7n806wm_j0hr0000gq/T/electron-packager/darwin-x64/Calculator-darwin-x64/Electron.app/Contents/Resources/app/ember/crossdoma
in.xml resulted in a MIME type of application/xml, which we don't know how to handle
✔ Compiling Application
✔ Preparing native dependencies
✔ Packaging Application
Making Electron project.
An error occured while making for target: dmg
spawn bless ENOENT
Error: spawn bless ENOENT
    at exports._errnoException (util.js:1034:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)

    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by bendemboski** [comment]
It looks like this is happening because the [bless](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/bless.8.html) command is not in your path, and `appdmg` (which we use to make `dmg`s) expects it to be. On my system, `which bless` gives me `/usr/sbin/bless`. I think if you ensure that `bless` is available in your path, this problem will go away.

**Comment by artemgurzhii** [comment]
Now I'm having this error.
```bash
Command failed: bless --folder /Volumes/Calculator --openfolder /Volumes/Calculator

ERROR: Illegal option --folder

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 413.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

Error: Command failed: bless --folder /Volumes/Calculator --openfolder /Volumes/Calculator

ERROR: Illegal option --folder

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 413.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by bendemboski** [comment]
It looks like this is outside the scope of `ember-electron`. `ember-electron` uses `electron-forge` which uses [appdmg](https://github.com/LinusU/node-appdmg) to build out `dmg`s. `appdmg` calls into `bless`. So it looks like the problem is that `appdmg` is calling `bless` in a way that your version of `bless` doesn't like. I'm not sure why that would be. Maybe it has to do with your version of OSX? This is really out of my (and `ember-electron`'s) domain -- I'd try asking for help over in `appdmg`.
