### ISSUE TITLE
Error: EPERM: operation not permitted, unlink 'electron-out/project/node_modules'

### ISSUE THREAD

**Issue by joshuairl** [felixrieseberg/ember-electron#249]
```
EPERM: operation not permitted, unlink 'electron-out/project/node_modules'
Error: EPERM: operation not permitted, unlink 'electron-out/project/node_modules'
    at Object.fs.unlinkSync (fs.js:1080:18)
    at SafeBuilder._unsymlinkModules (/Users/joshua/Projects/app-universal/node_modules/ember-electron/lib/models/safe-builder.js:16:10)
    at SafeBuilder.copyToOutputPath (/Users/joshua/Projects/app-universal/node_modules/ember-electron/lib/models/safe-builder.js:30:10)
    at /Users/joshua/Projects/app-universal/node_modules/ember-cli/lib/models/builder.js:182:21
    at tryCatch (/Users/joshua/Projects/app-universal/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/joshua/Projects/app-universal/node_modules/rsvp/dist/rsvp.js:554:13)
    at /Users/joshua/Projects/app-universal/node_modules/rsvp/dist/rsvp.js:629:16
    at flush (/Users/joshua/Projects/app-universal/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by joshuairl** [comment]
Actually, I think this has to do with the fact that some of my node modules were symlinked.
Going to try without them symlinked.

**Comment by andrewfan** [comment]
@joshuairl I have the same problem after updating to 2.x release
