### ISSUE TITLE
Can't position content in dmg (electron-forge-config.js)

### ISSUE THREAD

**Issue by debelop13** [felixrieseberg/ember-electron#250]
Hi!
I try to position .app, like I was using with electron-builder.. but is not working

      "contents": [
        {
          "x": 310,
          "y": 165,
          "type": "file",
          "path": "Install.app"
        }

It is saying 

> ember electron:make -prod --platform=darwin --arch=x64 --skip-package

Making Electron project.
An error occured while making for target: dmg
"Install.app" not found at: /var/folders/3m/j0my_tw930j0gk95nvc6sz400000gp/T/Install.app
Error: "Install.app" not found at: /var/folders/3m/j0my_tw930j0gk95nvc6sz400000gp/T/Install.app
    at /Users/sergio/Documents/Code/project/node_modules/appdmg/lib/appdmg.js:166:14
    at FSReqWrap.cb [as oncomplete] (fs.js:258:19)

Thanks!

**Comment by debelop13** [comment]
SOLVED:

contents: [
      {
        x: 310,
        y: 165,
        type: "file",
        path: path.join(__dirname, '../electron-out/Install-darwin-x64/Install.app')
      }
    ],
