### ISSUE TITLE
Failed to Find Electron While Packing

### ISSUE THREAD

**Issue by li-xinyang** [felixrieseberg/ember-electron#257]
```
ember electron:package
```

Produce the following error, seems the binary from GitHub is no longer available.

```
Packaging Electron project.
Downloading tmp-27093-0-electron-v1.6.7-oops.1-win32-ia32.zip
Error: GET https://github.com/electron/electron/releases/download/v1.6.7-oops.1/electron-v1.6.7-oops.1-win32-ia32.zip returned 404
Failed to find Electron v1.6.7-oops.1 for win32-ia32 at https://github.com/electron/electron/releases/download/v1.6.7-oops.1/electron-v1.6.7-oops.1-win32-ia32.zip
Error: Failed to find Electron v1.6.7-oops.1 for win32-ia32 at https://github.com/electron/electron/releases/download/v1.6.7-oops.1/electron-v1.6.7-oops.1-win32-ia32.zip
    at Request.<anonymous> (/Users/li-xinyang/Desktop/RR_VEE_2_Electron/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/Users/li-xinyang/Desktop/RR_VEE_2_Electron/node_modules/request/request.js:1074:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:551:20)
```

**Comment by debelop13** [comment]
Same here.

And we can't change electron version. #254

**Comment by bendemboski** [comment]
Is this still happening? I'm not seeing it locally, and our CI builds are passing, and they run an acceptance test that runs `ember electron:package` -- maybe it was a transitory problem?

**Comment by li-xinyang** [comment]
Yes, it is still happening to me.

```
Packaging Electron project.
Downloading tmp-25714-0-electron-v1.6.7-oops.1-darwin-x64.zip
Error: GET https://github.com/electron/electron/releases/download/v1.6.7-oops.1/electron-v1.6.7-oops.1-darwin-x64.zip returned 404
Failed to find Electron v1.6.7-oops.1 for darwin-x64 at https://github.com/electron/electron/releases/download/v1.6.7-oops.1/electron-v1.6.7-oops.1-darwin-x64.zip
Error: Failed to find Electron v1.6.7-oops.1 for darwin-x64 at https://github.com/electron/electron/releases/download/v1.6.7-oops.1/electron-v1.6.7-oops.1-darwin-x64.zip
    at Request.<anonymous> (/Users/li-xinyang/Desktop/RR_VEE_2_Electron/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/Users/li-xinyang/Desktop/RR_VEE_2_Electron/node_modules/request/request.js:1074:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:551:20)
```

**Comment by debelop13** [comment]
Hi @li-xinyang , you have to update dependencies in package.json. You have to install last version (1.6.8) of "electron-prebuilt-compile".

 ```
 "devDependencies": {
     ...
    "electron-prebuilt-compile": "1.6.8",
     ...
  }
```

**Comment by li-xinyang** [comment]
Thanks, @debelop13. Change the `electron-prebuild` version to the latest does solve the issue. However, I have no idea when I introduce this line of code into my `package.json` file.

**Comment by bendemboski** [comment]
This appears to be working now (with the last few `electron` versions). Please re-open if it's still causing you trouble.
