### ISSUE TITLE
Got frozen on step - 'Making Electron project'

### ISSUE THREAD

**Issue by ms4ever7** [felixrieseberg/ember-electron#265]
Hey again ,
I've tried to make installer for windows on windows, but there is also an issue which I don't know how to solve. So , here  is my error when i'am trying to  use ember electron:make command: 
```
An unhandled error has occurred inside Forge:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@6.9.5 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Roman\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (E:\dyegraph\dyegraph\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (E:\dyegraph\dyegraph\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at E:\dyegraph\dyegraph\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\dyegraph\\dyegraph\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.2" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\Users\Roman\AppData\Local\Temp\electron-packager\win32-x64\DyeGraph-win32-x64\resources\app\node_modules\node-sass
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

Failed with exit code: 1
Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@6.9.5 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Roman\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (E:\dyegraph\dyegraph\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (E:\dyegraph\dyegraph\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at E:\dyegraph\dyegraph\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\dyegraph\\dyegraph\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.2" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\Users\Roman\AppData\Local\Temp\electron-packager\win32-x64\DyeGraph-win32-x64\resources\app\node_modules\node-sass
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (E:\dyegraph\dyegraph\node_modules\spawn-rx\lib\src\index.js:262:84)
    at SafeSubscriber.__tryOrUnsub (E:\dyegraph\dyegraph\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (E:\dyegraph\dyegraph\node_modules\rxjs\Subscriber.js:197:26)
    at Subscriber._error (E:\dyegraph\dyegraph\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (E:\dyegraph\dyegraph\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (E:\dyegraph\dyegraph\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (E:\dyegraph\dyegraph\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (E:\dyegraph\dyegraph\node_modules\spawn-rx\lib\src\index.js:236:65)
    at SafeSubscriber.__tryOrSetError (E:\dyegraph\dyegraph\node_modules\rxjs\Subscriber.js:247:16)
    at SafeSubscriber.next (E:\dyegraph\dyegraph\node_modules\rxjs\Subscriber.js:187:27)
    at Subscriber._next (E:\dyegraph\dyegraph\node_modules\rxjs\Subscriber.js:125:26)
    at Subscriber.next (E:\dyegraph\dyegraph\node_modules\rxjs\Subscriber.js:89:18)
    at ReduceSubscriber._complete (E:\dyegraph\dyegraph\node_modules\rxjs\operator\reduce.js:119:30)
    at ReduceSubscriber.Subscriber.complete (E:\dyegraph\dyegraph\node_modules\rxjs\Subscriber.js:114:18)
    at MergeAllSubscriber._complete (E:\dyegraph\dyegraph\node_modules\rxjs\operator\mergeAll.js:94:30)
    at MergeAllSubscriber.Subscriber.complete (E:\dyegraph\dyegraph\node_modules\rxjs\Subscriber.js:114:18)
    at ArrayObservable._subscribe (E:\dyegraph\dyegraph\node_modules\rxjs\observable\ArrayObservable.js:116:24)
    at ArrayObservable.Observable._trySubscribe (E:\dyegraph\dyegraph\node_modules\rxjs\Observable.js:57:25)
    at ArrayObservable.Observable.subscribe (E:\dyegraph\dyegraph\node_modules\rxjs\Observable.js:45:27)
    at MergeAllOperator.call (E:\dyegraph\dyegraph\node_modules\rxjs\operator\mergeAll.js:63:23)
    at Observable.subscribe (E:\dyegraph\dyegraph\node_modules\rxjs\Observable.js:42:22)
    at ReduceOperator.call (E:\dyegraph\dyegraph\node_modules\rxjs\operator\reduce.js:74:23)
    at Observable.subscribe (E:\dyegraph\dyegraph\node_modules\rxjs\Observable.js:42:22)
    at ChildProcess.<anonymous> (E:\dyegraph\dyegraph\node_modules\spawn-rx\lib\src\index.js:236:29)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)```

I thought that it's because I don't have python env variavle, but with python in my path everything is ok.

**Comment by ms4ever7** [comment]
Problem was that i should install node-gyp and python variable to it.
Solved this just 5 min ago , but having an issue that it got frozen on step ```Making Electron Project``` . I had this problem on mac where was trying to make build for mac, it was there because I didn't know that i can make `ember electron:make` only for current operation system, 
Know I don't know what is the problem.

**Comment by dknutsen** [comment]
I think I'm seeing something similar trying to make Linux (Debian) installers in OSX. I've installed fakeroot and dpkg and everything appears to function normally. I can build/package/assemble/etc. just fine but when I try to make with the linux target it just hangs after the following output:
```
Packaging Electron project.
✔ Preparing to Package Application for arch: x64
✔ Compiling Application
✔ Preparing native dependencies
✔ Packaging Application
Making Electron project.
```

And when I say "hang" i mean for hours. Is there any way to debug this or figure out where it's stuck?

**Comment by bendemboski** [comment]
@dknutsen try running with `DEBUG=*` -- it will be super verbose, but should hopefully give you an idea of what it's doing when it hangs. You could also run `pstree` while it's hung to figure out if the `make` command is hanging on a sub-process.

**Comment by dknutsen** [comment]
Ha you weren't joking about verbose. In this case it looks like it's hanging on:
```
electron-installer-debian Creating package at /var/folders/n6/30w2_01s0yl3qw0v7rt_tpwc0000gp/T/electron-117426-83941-1xul1dj.nnbbl9dx6r/CityTrader (DEV)_3.2.8_amd64 +1s
electron-installer-debian Executing command fakeroot dpkg-deb --build /var/folders/n6/30w2_01s0yl3qw0v7rt_tpwc0000gp/T/electron-117426-83941-1xul1dj.nnbbl9dx6r/CityTrader (DEV)_3.2.8_amd64 +1ms
```

Guess I'll try playing around with fakeroot a bit

**Comment by dknutsen** [comment]
I'm guessing it's my package name, not very fs friendly

**Comment by dknutsen** [comment]
That was it, dumb call on my part. Thanks for the debug help @bendemboski!
