### ISSUE TITLE
UglifyJS doesn't handle ES6 code. The Broccoli Plugin: [UglifyWriter] failed with:

### ISSUE THREAD

**Issue by xn** [felixrieseberg/ember-electron#277]
I can run `ember electron` just fine.

When I run `ember electron:make -prod` I get:
```
Build failed.
File: assets/vendor.js (108794:20)
The Broccoli Plugin: [UglifyWriter] failed with:
SyntaxError: The Broccoli Plugin: [UglifyWriter] failed with:
    at JS_Parse_Error.get (<anonymous>:86:23)
    at writeError (/Users/xn/sites/patentdive/contraption/client/node_modules/console-ui/lib/write-error.js:23:23)
    at UI.writeError (/Users/xn/sites/patentdive/contraption/client/node_modules/console-ui/lib/index.js:159:3)
    at CLI.logError (/Users/xn/sites/patentdive/contraption/client/node_modules/ember-cli/lib/cli/cli.js:273:13)
    at tryCatch (/Users/xn/sites/patentdive/contraption/client/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/xn/sites/patentdive/contraption/client/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/Users/xn/sites/patentdive/contraption/client/node_modules/rsvp/dist/rsvp.js:522:7)
    at publishRejection (/Users/xn/sites/patentdive/contraption/client/node_modules/rsvp/dist/rsvp.js:457:3)
    at flush (/Users/xn/sites/patentdive/contraption/client/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I dug through `node_modules` and was able to get get to this error:
`Unexpected token: operator (>) on package`

which led me to #41 

It is trying to uglify electron-debug, which is installed as a devDependency.

Which led me here: https://github.com/sindresorhus/electron-debug/issues/39

Is this a bug or is electron-debug simply not compatible with ember-electron?

Thanks,
xn

**Comment by pichfl** [comment]
Which version of Ember Electron / Ember / Ember CLI do you use? 

Actually, turns out it doesn't matter. You are spot on with the linked issue of electron-debug.

You might want to disable Uglify in Ember CLI. While minified code may be faster (or slower, it depends) it should not be that much of a difference (see before) and since you don't send your Ember code over the internet, you should be fine anyway. Follow the official guide of Ember-CLI to [disable minification](https://ember-cli.com/user-guide/#minifying).

Uglify does not handle ES6 gracefully. If you absolutely insist on minification replace ember-cli-uglify with [ember-cli-babili](https://github.com/ember-cli/ember-cli-babili) which does minification in a ES6-friendly way.

**Comment by xn** [comment]
This is really intractable. I'm in an npm hall of mirrors dependency hell. Getting rid of the finger printing and the entire hosted side of the app for now. You can close this, I'm not going to pursue getting this to work in the short to mid term. Thanks.

**Comment by pichfl** [comment]
The latest releases of ember-cli-uglify should work with the newer stuff as well. I'm closing this.
