### ISSUE TITLE
Installer error on electron-forge

### ISSUE THREAD

**Issue by elias94** [felixrieseberg/ember-electron#288]
Run ` ember install ember-electron` on a new ember-cli project.
```
NPM: Installed ember-electron
installing ember-electron
  create ember-electron/.compilerc
  create ember-electron/main.js
  create ember-electron/test-main.js
  create testem-electron.js
Project has forge config
NPM: Installed devtron@^1.4.0
NPM: Installed electron-protocol-serve@^1.3.0
Installed electron build tools
Created ember-electron resource dirs
Installed addon package.
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/tmp/electron-forge/.runtime.config'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at BasicConfigStore.reset (/xxx/node_modules/electron-forge/dist/util/config.js:86:27)
    at process.<anonymous> (/xxx/node_modules/electron-forge/dist/util/config.js:56:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at processEmit [as emit] (/xxx/node_modules/signal-exit/index.js:149:35)
```
```
ember-cli: 2.14.2
node: 6.11.2
os: linux x64
```

**Comment by bendemboski** [comment]
Sorry we didn't respond to this sooner! We've made some improvements to the install process -- can you try with the latest `ember-electron`? Note that because of #326 you'll need to make sure your `package.json` has a `productName` specified before install `ember-electron`.

**Comment by anulman** [comment]
Thanks @bendemboski for jumping in. @elias94 wondering also if your npm is installed globally, vs. per-user? I find it curious that it's looking at `/tmp/electron-forge`, vs a more typically user-readable dir.

**Comment by jacobq** [comment]
Closing due to lack of response / inactivity.
