### ISSUE TITLE
Ember electron gives **Electron failed to install correctly **

### ISSUE THREAD

**Issue by Zorig** [felixrieseberg/ember-electron#290]
Hi, after a `ember install ember-electron` gives **can not find package** struggle finally able to install ember-electron somehow(`yarn add --dev ember-electron`, `npm install ember-electron`. Then my node-sass crashed after fixing node-sass via `npm rebuild node-sass` `ember electron` command gives me following error. 

```
Starting Electron...
You are using the depreceated electron-rebuild API, please switch to using the options object instead
/Users/zorig/projects/playweb/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/Users/zorig/projects/playweb/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zorig/projects/playweb/node_modules/electron-prebuilt-compile/lib/cli.js:4:17)
    at Module._compile (module.js:570:32)
Electron exited.
```

ps: // i just installed 2.2.1 and it works fine, ember version is 2.14.1

**Comment by bendemboski** [comment]
It sounds like this issue went away for you when you installed a newer `ember-electron`? I'm going to close this issue -- re-open if it's still causing you problems.
