### ISSUE TITLE
require('electron') cannot find module

### ISSUE THREAD

**Issue by GiovanniL19** [felixrieseberg/ember-electron#319]
Hi,

I attempting to open the users downloads folder from a controller called dashboard. The issue I am having is when I require electron, I get the following error:

```
Error while processing route: index Cannot find module...
 at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/node_modules/electron-prebuilt-compile/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at win.require.args (serve://dist/:81:18)
    at Class._extractDefaultExport (serve://dist/assets/vendor.js:92244:20)
    at Class.resolveOther (serve://dist/assets/vendor.js:91965:32)
    at Class.superWrapper [as resolveOther] (serve://dist/assets/vendor.js:57002:22)
    at Class.resolveController (serve://dist/assets/vendor.js:24342:19)
```

Example require code is:

```
const { shell } = require('electron')
shell.openExternal('https://github.com')
```

[Code Source](https://github.com/electron/electron/blob/master/docs/api/shell.md)

I'm not sure what I am missing, any advice will be appreciated please

Thank you!

**Comment by GiovanniL19** [comment]
Found [the fix](https://stackoverflow.com/a/34396466/1935433)

I used the following:

```
const electron = window.require('electron');
```
