### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by chrism** [felixrieseberg/ember-electron#320]
I've just tried to install ember-electron using the standard

`ember install ember-electron`

But got this error:

    Yarn: Installed ember-electron
    installing ember-electron
      create ember-electron/.compilerc
      create ember-electron/main.js
      create ember-electron/test-main.js
      create testem-electron.js
    Project needs forge config
    _fsExtra2.default.pathExists is not a function
    TypeError: _fsExtra2.default.pathExists is not a function
        at _callee8$ (/Users/username/git/projectname/node_modules/electron-forge/dist/api/import.js:115:38)
        at tryCatch (/Users/username/git/projectname/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:65:40)
        at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/username/git/projectname/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:299:22)
        at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/username/git/projectname/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:117:21)
        at GeneratorFunctionPrototype.tryCatcher (/Users/username/git/projectname/node_modules/bluebird/js/release/util.js:16:23)
        at PromiseSpawn._promiseFulfilled (/Users/username/git/projectname/node_modules/bluebird/js/release/generators.js:97:49)
        at /Users/username/git/projectname/node_modules/bluebird/js/release/generators.js:201:15
        at /Users/username/git/projectname/node_modules/electron-forge/dist/api/import.js:653:17
        at EmberElectronBlueprint._installElectronTooling (/Users/username/git/projectname/node_modules/ember-electron/blueprints/ember-electron/index.js:61:12)
        at _checkForgeConfig.then (/Users/username/git/projectname/node_modules/ember-electron/blueprints/ember-electron/index.js:26:24)
        at tryCatcher (/Users/username/git/projectname/node_modules/ember-electron/node_modules/rsvp/dist/rsvp.js:329:19)
        at invokeCallback (/Users/username/git/projectname/node_modules/ember-electron/node_modules/rsvp/dist/rsvp.js:507:31)
        at publish (/Users/username/git/projectname/node_modules/ember-electron/node_modules/rsvp/dist/rsvp.js:493:7)
        at flush (/Users/username/git/projectname/node_modules/ember-electron/node_modules/rsvp/dist/rsvp.js:2432:5)
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickCallback (internal/process/next_tick.js:98:9)

I tried to run `ember electron`anyway to see if it might still work but get this error:

    Your package.json doesn't contain 'config.forge'. Please re-run the ember-electron blueprint ('ember g ember-electron').
    Error: Your package.json doesn't contain 'config.forge'. Please re-run the ember-electron blueprint ('ember g ember-electron').
        at assembleTree (/Users/username/git/projectname/node_modules/ember-electron/lib/utils/assemble-tree.js:62:11)
        at Class.postprocessTree (/Users/username/git/projectname/node_modules/ember-electron/index.js:51:14)
        at projectOrAddon.addons.reduce (/Users/username/git/projectname/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
        at Array.reduce (native)
        at addonProcessTree (/Users/username/git/projectname/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
        at EmberApp.addonPostprocessTree (/Users/username/git/projectname/node_modules/ember-cli/lib/broccoli/ember-app.js:661:12)
        at EmberApp.toTree (/Users/username/git/projectname/node_modules/ember-cli/lib/broccoli/ember-app.js:1814:17)
        at module.exports (/Users/username/git/projectname/ember-cli-build.js:24:14)
        at Builder.setupBroccoliBuilder (/Users/username/git/projectname/node_modules/ember-cli/lib/models/builder.js:56:19)
        at Builder (/Users/username/git/projectname/node_modules/ember-cli/lib/models/builder.js:30:10)
        at Builder (/Users/username/git/projectname/node_modules/ember-electron/lib/models/builder.js:35:5)
        at Class._buildAndWatch (/Users/username/git/projectname/node_modules/ember-electron/lib/commands/electron.js:54:21)
        at Class.run (/Users/username/git/projectname/node_modules/ember-electron/lib/commands/electron.js:48:17)
        at resolve (/Users/username/git/projectname/node_modules/ember-cli/lib/models/command.js:317:20)
        at initializePromise (/Users/username/git/projectname/node_modules/rsvp/dist/rsvp.js:567:5)
        at new Promise (/Users/username/git/projectname/node_modules/rsvp/dist/rsvp.js:1039:33)

Do you have any suggestions why this might be happening?

Can provide any additional information if it could be useful—it's a very simple project using the most recent (2.16.2) versions of ember-cli, ember & ember-data.

Many thanks.

**Comment by chrism** [comment]
In case anyone has this same issue

I found that running

`ember install ember-electron@2.7.1`

instead (the latest release at the time of writing) resolved it.

**Comment by bendemboski** [comment]
Reopening because this is definitely an issue with the latest ember-electron that needs to be addressed (and I think I have a fix coming shortly...)
