### ISSUE TITLE
Packages are not copied to build during "ember electron:package"

### ISSUE THREAD

**Issue by synic** [felixrieseberg/ember-electron#323]
Using ember-electron@2.7.2
npm version 4.2.0
node version 7.10.0

Testing the app with `ember electron`, everything works fine.

If I then run `ember electron:package`, and then cd to `electron-out/overseer-linux-x64` and run `./overseer`, I get the following error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'jsonfile'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/synic/Projects/ember/overseer/electron-out/overseer-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/synic/Projects/ember/overseer/electron-out/overseer-linux-x64/resources/app/node_modules/electron-window-state/index.js:5:16)
    at Object.<anonymous> (/home/synic/Projects/ember/overseer/electron-out/overseer-linux-x64/resources/app/node_modules/electron-window-state/index.js:176:3)
    at Module._compile (module.js:571:32)
    at Object.require.extensions.(anonymous function) [as .js] (/home/synic/Projects/ember/overseer/electron-out/overseer-linux-x64/resources/app/node_modules/electron-compile/lib/require-hook.js:77:14)
    at Module.load (module.js:488:32)
```

`jsonfile` is in `node_modules`, but it is NOT in `electron-out/overseer-linux-x64/resources/app/node_modules`.

It seems like a LOT of the modules that are required have not been copied.  What have I done wrong?

**Comment by synic** [comment]
Nvm, I upgraded npm.  Seems to be ok now.
