### ISSUE TITLE
app.asar/ember ENOENT

### ISSUE THREAD

**Issue by danidr** [felixrieseberg/ember-electron#343]
Hello,
Currently running on `ember 2.18` and `ember-electron 2.7.3`. I am developing a web app which is also packaged as an Electron app, which I compile once every couple of months, therefore my guess is that my last WORKING compile was with either `ember-electron 2.7.1` or `ember-electron 2.7.2`.
After updating to `ember-electron 2.7.3`, and after compiling the app, on Windows I get the following error message on the Chromium console on app start:

`
vendor.js:45796 DEBUG: -------------------------------
vendor.js:45796 DEBUG: Ember             : 2.18.0
vendor.js:45796 DEBUG: Ember Data        : 2.18.0
vendor.js:45796 DEBUG: jQuery            : 3.3.1
vendor.js:45796 DEBUG: Ember Bootstrap   : 1.2.1
vendor.js:45796 DEBUG: Ember Simple Auth : 1.5.1
vendor.js:45796 DEBUG: -------------------------------
vendor.js:303391 Error loading Ember Inspector Error: ENOENT, node_modules\ember-inspector\dist\chrome not found in C:\App-win32-x64\resources\app.asar
    at notFoundError (ELECTRON_ASAR.js:114:19)
    at Object.fs.lstat (ELECTRON_ASAR.js:268:16)
    at installEmberInspector (serve://dist/assets/vendor.js:303389:8)
    at HTMLDocument.document.addEventListener (serve://dist/assets/vendor.js:303437:5)
fs.lstat @ vendor.js:303391
fs.js:1396 Uncaught Error: watch C:\App-win32-x64\resources\app.asar\ember ENOENT
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at watch (serve://dist/assets/vendor.js:303356:8)
    at fs.stat (serve://dist/assets/vendor.js:303421:9)
    at ELECTRON_ASAR.js:271:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
vendor.js:25217 [Violation] 'setTimeout' handler took 120ms
`

Any idea of what this might be? Can't wrap my head around it, really... Already tried to flush npm cache and tmp folder.

**Comment by jacobq** [comment]
Hi & sorry to hear you are having this problem. As you probably know, `ENOENT` means there was an error finding the file/directory requested. Since you're seeing this on the front-end (electron/chrome devtools console) it seems likely to be related to the livereload feature. (Perhaps [this line](https://github.com/felixrieseberg/ember-electron/blob/46ad30457ed18e86457cf68c890b2258443448af/app/electron/reload.js#L32).) Could you please provide some more information, such as:

* What command did you use to build/run? Was it `ember electron`? (vs. `ember electron:test`, `ember s`, etc.)
* Are you running the command as a use with full/administrator privileges?
* What do you see if you run `ember electron:assemble` then look in the `electron-out/project/` directory. Is there an `ember` folder?
* Which parts of the code are associated with the stack trace calls? (the line numbers aren't helpful here since `vendor.js` is custom build with your app's assets) e.g. set a breakpoint at `vendor.js:303356`

**Comment by danidr** [comment]
Yep, I thought about a bug in the ASAR packaging at first, but then even in that case I wouldn't know where to get the right "ember" folder from...
By the way, I tried reverting to` ember-electron 2.7.1`, and it still didn't work; still, I can't guess what in MY code could make this go wrong...
- I built with` electron:package --platform=win32` (from a Linux VM) and then tested it on Windows 10 with all latest updates.
- Tried with administrator privileges, same result.
- `electron-out/project` contains the ember folder after ember `electron:assemble`.
- Parts of code associated with that stack trace are (going up the call stack):
```javascript
function setupLivereload() {
...
fs.watch(dirname, { recursive: true }, () => window.location.reload());
```
```javascript
function installEmberInspector() {
...
fs.stat(dianame, (err/* , stat */) => {
  if (!err) {
    watch();
```
Thank you for your help,

Daniele

**Comment by jacobq** [comment]
Do you see the same error when you run `ember electron` (development mode)? I'm not sure what's going on, but it seems like your app (not necessarily your code -- could be in ember-electron or something else) is trying to load the dev tools in a production build (and, of course, they're not there). If this is reproducible with an empty project then it's probably a bug.

It might be easier to ask for help on the community slack chat's e-electron channel:
https://emberjs.com/community/

**Comment by danidr** [comment]
Makes sense; I'll try and look up which of my add-ons uses dev tools in production, may take quite a long time. In fact, I DON'T get the same error running `ember electron` (I get a blank page with no errors, but I'm sure that's something wrong in my code).
Thank you for your assistance anyway!

**Comment by jacobq** [comment]
The fact that it doesn't happen with `ember electron` suggests that it is indeed related to `installEmberInspector` getting called in production for some reason. Maybe one of the project collaborators will be able to help you out further if you can't find the culprit in your deps.

**Comment by danidr** [comment]
Okay, found the solution: apparently, running `ember electron:package --platform=win32` was NOT setting the environment to `production`. The entire command works: `ember electron:package --platform=win32 --environment=production`
