### ISSUE TITLE
Does not work in new project - Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by jackmatt2** [felixrieseberg/ember-electron#39]
I just tried this out on a brand new project but am getting the following error.

```
$ember --version
version: 2.3.0
node: 0.12.7
os: darwin x64

$ember new electron
...
$cd electron
$ember install ember-electron
```

```
/Users/jack/git/electron/node_modules/ember-electron/lib/helpers/remote-debug-script.js:2
    return `<script src="http://${host}:${port}/socket.io/socket.io.js" type="
           ^
Unexpected token ILLEGAL
/Users/jack/git/electron/node_modules/ember-electron/lib/helpers/remote-debug-script.js:2
    return `<script src="http://${host}:${port}/socket.io/socket.io.js" type="
           ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jack/git/electron/node_modules/ember-electron/index.js:7:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by felixrieseberg** [comment]
Hey Jack, thanks for reporting! Simple fix on both of our sides: You just need to upgrade Node to at least 4.0 (the current stable), I just need to update the package.json to ensure that people are running a supported version of Node ;-)

(Background info: While Electron runs Node 5, the Ember Electron commands are still being executed with whatever Node version you have installed)

**Comment by felixrieseberg** [comment]
Interestingly, it's already in the `package.json` - npm should have warned you during installation. Closing for now, but feel free to reach out if you have any trouble after upgrading Node!

**Comment by jackmatt2** [comment]
Yes, it does give the warning:

```
Installing packages for tooling via npmWARN engine ember-electron@1.1.1: wanted: {"node":">= 4.0.0"} (current: {"node":"0.12.7","npm":"2.14.10"})
```

I am in the habit of ignoring npm warnings because they show up all the time for false negatives.
