### ISSUE TITLE
Unexpected token: operator (>) on package

### ISSUE THREAD

**Issue by oskarrough** [felixrieseberg/ember-electron#41]
Hi, I'm getting the following error when I run `ember electron:package`.

```
➜  xxx git:(electron) ✗ ember electron:package
version: 2.3.0
Build failed.
File: assets/vendor.js (62957:36)
Unexpected token: operator (>)
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/xxx/Sites/xxx/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1508:18)
    at js_error (eval at <anonymous> (/Users/xxx/Sites/xxx/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1516:11)
    at croak (eval at <anonymous> (/Users/xxx/Sites/xxx/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2008:9)
```

From what I can tell, it's related to uglify not being able to minify es6 ([?](https://github.com/mishoo/UglifyJS2/issues/659)). But `ember electron` and `ember build -p` works fine which is why I'm asking here.

**Comment by felixrieseberg** [comment]
Thanks for reporting! I finally managed to hunt the error down. This is now fixed in 1.1.1 (which was just released).

**Comment by xn** [comment]
I seem to be getting this on windows.

**Comment by xn** [comment]
@felixrieseberg

**Comment by pichfl** [comment]
Please don't piggyback onto a closed issue. Open up a new one referencing this and provide more details of your error. Also provide the version number for Ember Electron, Ember-CLI, Ember.js you have in use. This error is more than a year old and Ember Electron changed a lot since then.

**Comment by xn** [comment]
Great thanks. Will do.
