### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by devlo** [felixrieseberg/ember-electron#50]
```
version: 2.4.2
Build failed.
File: assets/vendor.js (64148:8)
The Broccoli Plugin: [object Object] failed with:
Error
at new JS_Parse_Error (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :1508:18)
at js_error (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :1516:11)
at croak (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2008:9)
at token_error (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2016:9)
at unexpected (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2022:9)
at semicolon (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2042:43)
at simple_statement (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2222:73)
at eval (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2095:19)
at eval (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2055:24)
at block_ (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2335:20)
at eval (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2308:25)
at function_ (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2313:15)
at expr_atom (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2521:24)
at maybe_unary (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2691:19)
at expr_ops (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2726:24)
at maybe_conditional (eval at (C:\application\node_modules\ember-cli-uglify\node_modules\broccoli-uglify-sourcemap\node_modules\uglify-js\tools\node.js:1:0), :2731:20)

The broccoli plugin was instantiated at:
undefined
```

What i did is i made new dir and:

```
ember init
ember install ember-electron
ember electron:package
```

And got this error.

**Comment by felixrieseberg** [comment]
Well that sucks... Thanks for reporting! Which version of ember-cli are you using?

**Comment by felixrieseberg** [comment]
Actually, I can confirm the error. I'll update you once I fixed it.

**Comment by devlo** [comment]
That was fast :) Thank you.

**Comment by felixrieseberg** [comment]
One quick question: Are you running Windows?

**Comment by devlo** [comment]
Yes, Windows 10.

**Comment by felixrieseberg** [comment]
@devlo: I think I found the issue. Could you install 1.2.3 and tell me if that fixes it for you?

**Comment by devlo** [comment]
Sure, doing it right now.

**Comment by devlo** [comment]
It's fixed now, thanks!

**Comment by felixrieseberg** [comment]
Thanks for reporting!

**Comment by marcemira** [comment]
Hey guys, having the same error on linux, ember-cli: 2.6.0-beta.2 :/
