### ISSUE TITLE
__dirname is not defined in blueprint template

### ISSUE THREAD

**Issue by kevinmickey** [felixrieseberg/ember-electron#56]
Same issue brought up in by gordonbisnor in #36, but it seems unrelated to the original issue that was closed, so I'm opening this issue.

https://stackoverflow.com/questions/8817423/node-dirname-not-defined

I've tried using node v5.2.0 and v5.11.0.

I run ember install ember-electron and get:

>   [?] Overwrite config/environment.js? No, skip
  skip config/environment.js
  create electron.js
  create tests/electron.js
  create tests/package.json
__dirname is not defined (Error in blueprint template: /Users/kevin/Web/mycms/netlify-cms/node_modules/ember-electron/blueprints/ember-electron/files/electron.js)
ReferenceError: __dirname is not defined (Error in blueprint template: /Users/kevin/Web/mycms/netlify-cms/node_modules/ember-electron/blueprints/ember-electron/files/electron.js)
    at eval (eval at <anonymous> (/Users/kevin/Web/mycms/netlify-cms/node_modules/ember-cli/node_modules/lodash/string/template.js:214:12), <anonymous>:8:10)
    at processTemplate (/Users/kevin/Web/mycms/netlify-cms/node_modules/ember-cli/lib/models/file-info.js:13:52)
    at /Users/kevin/Web/mycms/netlify-cms/node_modules/ember-cli/lib/models/file-info.js:94:20
    at lib$rsvp$$internal$$tryCatch (/Users/kevin/Web/mycms/netlify-cms/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/kevin/Web/mycms/netlify-cms/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/kevin/Web/mycms/netlify-cms/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/kevin/Web/mycms/netlify-cms/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by timbaas** [comment]
I'm experiencing the same issue on node v4.2.6

**Comment by JoshuaTyree** [comment]
@felixrieseberg I'm confirming @timbaas 's findings.  Upgrading to Ember-CLI 2.5.0 fixes the problem. Should we update the main documentation to detail requirements?  I can submit a PR if you prefer.

**Comment by felixrieseberg** [comment]
I also just pushed a little update that uses a time-proven workaround to deal with `__dirname` undefined. If one of you still has the error, could you give it a try and see if that fixes things?

@JoshuaTyree: If that's a working solution, I'd very much appreciate a PR!
