### ISSUE TITLE
ember electron:test fails

### ISSUE THREAD

**Issue by pascalw** [felixrieseberg/ember-electron#6]
I have a new Ember CLI project where I added ember-electron to.
Now when I run `ember electron:test` or `ember electron:test --server` I get the following error:

```
Building.ENOENT: no such file or directory, lstat '/Users/Pascal/projects/ember-electron/tmp/funnel-input_base_path-JfSENpV2.tmp/0/package.json'
Error: ENOENT: no such file or directory, lstat '/Users/Pascal/projects/ember-electron/tmp/funnel-input_base_path-JfSENpV2.tmp/0/package.json'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at symlink (/Users/Pascal/projects/ember-electron/node_modules/symlink-or-copy/index.js:63:26)
    at Function.symlinkOrCopySync [as sync] (/Users/Pascal/projects/ember-electron/node_modules/symlink-or-copy/index.js:58:5)
    at Funnel._copy (/Users/Pascal/projects/ember-electron/node_modules/broccoli-funnel/index.js:398:19)
    at Funnel.processFile (/Users/Pascal/projects/ember-electron/node_modules/broccoli-funnel/index.js:381:8)
    at Funnel.applyPatch [as _applyPatch] (/Users/Pascal/projects/ember-electron/node_modules/broccoli-funnel/index.js:298:12)
    at Funnel.<anonymous> (/Users/Pascal/projects/ember-electron/node_modules/broccoli-funnel/index.js:250:10)
    at Array.forEach (native)
    at Funnel.processFilters (/Users/Pascal/projects/ember-electron/node_modules/broccoli-funnel/index.js:249:9)
```

I'm using Ember CLI 1.13.13 with Ember 2.2.0. Any idea what could be the issue?

**Comment by pascalw** [comment]
Hm ok I now realise that regardless of the issue I was having above my actual problem was that that the docs are a little confusing/lacking.

I was just trying to launch a dev environment which apparently is done by running `ember electron`. Now I'm still not sure how exactly this is supposed to work? I had the impression that an Ember server would also be started since the `electron.js` references `http://localhost:5000` however this does not seem to be the case? Would love to get some pointers on how to actually use this :blush:

**Comment by hglattergotz** [comment]
@pascalw Have you made any progress on this?

**Comment by pascalw** [comment]
@hglattergotz I have not. Haven't messed around with it anymore either, I was just playing around.

**Comment by felixrieseberg** [comment]
I'm currently in the process of writing up some docs, I'll post them later today :+1:

**Comment by felixrieseberg** [comment]
Hey, just a quick update: I had a small bug in the project due to Ember Cli updates - if you run `ember install ember-electron` again, it'll pull down the new version and run the blueprint generation correctly. In detail, the issue you had was that the `tests` folder was missing the required `package.json` and `electron.js` files.

I also updated the docs and update dependencies, so everything should be better now :rocket:
