### ISSUE TITLE
Electron blueprints need to call super

### ISSUE THREAD

**Issue by leepfrog** [felixrieseberg/ember-electron#72]
When using ember-electron on a fresh ember-init project, I receive these errors:

```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `electron`
    at  node_modules/ember-cli/lib/models/project.js:404:38
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `electron:test`
    at node_modules/ember-cli/lib/models/project.js:404:38
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `electron:package`
    at node_modules/ember-cli/lib/models/project.js:404:38
```

**Comment by felixrieseberg** [comment]
Thanks for the report, I wasn't aware! This is now fixed.
