### ISSUE TITLE
"Cannot read property 'isEmberCLIProject' of undefined" when running "ember electron"

### ISSUE THREAD

**Issue by timmyomahony** [felixrieseberg/ember-electron#73]
I'm trying to get started with Ember + Electron. After setting up a new project with:
    
    ember new my-app

followed by 

    ember install ember-electron

I've tried to run the project with 

    ember electron

but I'm getting the error:

```
Cannot read property 'isEmberCLIProject' of undefined
TypeError: Cannot read property 'isEmberCLIProject' of undefined
    at CoreObject.extend.init (/path/to/app/node_modules/ember-cli/lib/models/command.js:53:40)
    at CoreObject.superWrapper [as init] (/path/to/app/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.superFn (/path/to/app/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:17:33)
    at CoreObject.module.exports.init (/path/to/app/node_modules/ember-electron/lib/commands/electron.js:17:18)
    at CoreObject.superWrapper [as init] (/path/to/app/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/path/to/app/node_modules/ember-cli/node_modules/core-object/core-object.js:32:33)
    at CLI.<anonymous> (/path/to/app/node_modules/ember-cli/lib/cli/cli.js:39:19)
    at lib$rsvp$$internal$$tryCatch (/path/to/app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/path/to/app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/path/to/app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/path/to/app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

My Ember CLI:

```
ember-cli: 2.6.0-beta.3
node: 5.7.1
os: darwin x64
```

I'm admittedly extremely new to Electron so I may be missing something pretty obvious?

**Comment by timmyomahony** [comment]
Noticed that `ember-cli@2.3.0` is required in the `package.json` while I'm running `2.6.0` so I installed the older `ember-cli` locally and ran

    ./node_modules/ember-cli/bin/ember init
    ./node_modules/ember-cli/bin/ember install ember-electron
    ./node_modules/ember-cli/bin/ember electron

and now I'm getting a slightly different error

```
this._super is not a function
TypeError: this._super is not a function
    at Class.module.exports.init (/path/to/app/node_modules/ember-electron/lib/commands/electron.js:17:18)
    at new Class (/path/to/app/node_modules/core-object/core-object.js:18:12)
    at CLI.<anonymous> (/path/to/app/node_modules/ember-cli/lib/cli/cli.js:41:19)
    at lib$rsvp$$internal$$tryCatch (/path/to/app/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/path/to/app/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/path/to/app/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/path/to/app/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

**Comment by felixrieseberg** [comment]
Thanks for the report, this is totally not your fault - you found a bug that snuck into the patch an hour ago - it's fixed in a patch that just went live. If you install `ember-electron@1.6.3`, everything should be okay for you!

**Comment by timmyomahony** [comment]
Amazing, thanks for the quick update. It's working perfectly now.
