### ISSUE TITLE
Code sign failed; please retry manually. Error: No identity found for signing.

### ISSUE THREAD

**Issue by mateodelnorte** [felixrieseberg/ember-electron#82]
Hi, 

Not sure if this is the correct place for this issue, however I'm getting the following error when attempting to build electron. 

Is this a configuration issue, or perhaps a bug?

```
Installing production dependencies into Electron Build Package
electron-debug@1.0.1 tmp/electron-build-tmp/node_modules/electron-debug
├── electron-localshortcut@0.6.1
└── electron-is-dev@0.1.1
Installed and bundled electron-debug@^1.0.0
Installing Electron headers for version 1.1.2
Recompiling native dependencies
The cache parameter is deprecated, use download.cache instead
Packaging app for platform darwin x64 using electron v0.37.5
Code sign failed; please retry manually. Error: No identity found for signing.
    at /Users/mateodelnorte/development/cardstack-desktop/node_modules/electron-osx-sign/index.js:49:28
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

I'm on El Capitan version 10.11.5 (15F34)
node --version: v6.3.0
electron --version: v1.3.1

**Comment by felixrieseberg** [comment]
Hey, this is probably a configuration issue - if you check out your `package.json`, do you see anything that looks like a codesigning reference?

```
                'osx-sign': {
                    identity: null,
                    entitlements: null,
                    'entitlements-inherit': null
                },
```

**Comment by mateodelnorte** [comment]
It was an issue with my Apple Developer account, actually. Turns out there was some internal Apple systems bug converting my account from a Safari Developers account to the new type. :-|
